// <autogenerated>
//   This file was generated by T4 code generator ContractCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Threading.Tasks;

using SqlSugar;

using TomNet.SqlSugarCore.Entity;
using TomNet.App.Model.DB.Identity;


namespace TomNet.App.Core.Contracts.Identity
{
    /// <summary>
    /// 契约接口 Role
    /// </summary> 
	public partial interface IRoleContract
    { 
		/// <summary>
        /// 获取 当前单元操作对象
        /// </summary>
        IUnitOfWork UnitOfWork { get; }

		/// <summary>
        /// 获取 当前实体类型的查询数据集
        /// </summary>
        ISugarQueryable<Role> Entities { get; }

        //=============================== 实现方法 ===============================
        /// <summary>
        /// 新增
        /// </summary>
        /// <returns>操作影响的行数</returns>
        int Insert(Role entity);

        Task<int> InsertAsync(Role entity);


        /// <summary>
        /// 批量新增
        /// </summary>
        /// <returns>操作影响的行数</returns>
        int Insert(List<Role> entities);

        Task<int> InsertAsync(List<Role> entities);


        /// <summary>
        /// 批量新增
        /// </summary>
        /// <returns>操作影响的行数</returns>
        int Insert(Role[] entities);

        Task<int> InsertAsync(Role[] entities);


        /// <summary>
        /// 新增并返回实体
        /// </summary>
        /// <returns>操作影响的行数</returns>
        Role InsertReturnEntity(Role entity);

        Task<Role> InsertReturnEntityAsync(Role entity);


        /// <summary>
        /// 修改（主键是更新条件）
        /// </summary>
        /// <param name="entity"> 实体对象（必须指定主键特性 [SugarColumn(IsPrimaryKey=true)]）</param> 
        /// <param name="ignoreColumns">不更新的列</param>
        /// <returns>操作影响的行数</returns>
        int Update(Role entity, string[] ignoreColumns = null);

        Task<int> UpdateAsync(Role entity, string[] ignoreColumns = null);


        /// <summary>
        /// 修改（主键是更新条件）
        /// </summary>
        /// <param name="entitys">实体对象集合（必须指定主键特性 [SugarColumn(IsPrimaryKey=true)]） </param> 
        /// <param name="ignoreColumns">不更新的列</param>
        /// <returns>操作影响的行数</returns>
        int Update(List<Role> entitys, string[] ignoreColumns = null);

        Task<int> UpdateAsync(List<Role> entitys, string[] ignoreColumns = null);


        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="update">实体对象</param> 
        /// <param name="predicate">条件</param>  
        /// <returns>操作影响的行数</returns>
        int Update(Expression<Func<Role, Role>> update, Expression<Func<Role, bool>> predicate = null);

        Task<int> UpdateAsync(Expression<Func<Role, Role>> update, Expression<Func<Role, bool>> predicate = null);


        /// <summary>
        /// 根据实体删除
        /// </summary>
        /// <param name="entity">实体对象</param>
        /// <returns>操作影响的行数</returns>
        int Delete(Role entity);

        Task<int> DeleteAsync(Role entity);


        /// <summary>
        /// 根据主键删除
        /// </summary>
        /// <param name="id">主键</param>
        /// <returns>操作影响的行数</returns>
        int Delete(int id);

        Task<int> DeleteAsync(int id);


        /// <summary>
        /// 根据主键数组删除
        /// </summary>
        /// <param name="ids">主键数组</param>
        /// <returns>操作影响的行数</returns>
        int Delete(int[] ids);

        Task<int> DeleteAsync(int[] ids);


        /// <summary>
        /// 根据条件删除
        /// </summary>
        /// <param name="predicate">删除条件</param>
        /// <returns>操作影响的行数</returns>
        int Delete(Expression<Func<Role, bool>> predicate);

        Task<int> DeleteAsync(Expression<Func<Role, bool>> predicate);


        /// <summary>
        /// 根据条件查询第一条符合条件的数据
        /// </summary>
        /// <param name="predicate">查询条件</param>
        Role GetFirst(Expression<Func<Role, bool>> predicate);

        Task<Role> GetFirstAsync(Expression<Func<Role, bool>> predicate);

	}
}
