// <autogenerated>
//   This file was generated by T4 code generator ServicePackCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Microsoft.Extensions.DependencyInjection;

using TomNet.Core.Packs;
using TomNet.App.Core.Contracts.Security;
using TomNet.App.Core.Services.Security;
using TomNet.App.Core.Contracts.Identity;
using TomNet.App.Core.Services.Identity;


namespace TomNet.App.Core
{
	public abstract class ServicePackBase : TomNetPack
    {
        /// <summary>
        /// 获取 模块级别，级别越小越先启动
        /// </summary>
        public override PackLevel Level => PackLevel.Application;

        public override int Order => 2;

        /// <summary>
        /// 将模块服务添加到依赖注入服务容器中
        /// </summary>
        /// <param name="services">依赖注入服务容器</param>
        /// <returns></returns>
        public override IServiceCollection AddServices(IServiceCollection services)
        {
			services.AddScoped<IRoleFunctionMapContract, RoleFunctionMapService>();
			services.AddScoped<IRoleContract, RoleService>();
			services.AddScoped<IUserInfoContract, UserInfoService>();
			services.AddScoped<IUserLoginContract, UserLoginService>();
			services.AddScoped<IUserRoleMapContract, UserRoleMapService>();
            return base.AddServices(services);
        }
    }

}
